# Generated by Django 4.1.7 on 2023-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_name", models.CharField(max_length=40, unique=True)),
                ("last_beat_time", models.DateTimeField()),
                ("task_payload", models.CharField(max_length=200)),
                ("task_end_time", models.DateTimeField()),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in-progress", "Wip"),
                            ("finished", "Finished"),
                            ("errored out", "Error"),
                            ("NA", "Na"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
            ],
        ),
    ]
