# Generated by Django 4.1.7 on 2023-03-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0002_jobtemplate_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fuzzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField()),
                ("name", models.CharField(max_length=50, unique=True)),
                ("filename", models.CharField(max_length=50)),
                ("file_size", models.CharField(max_length=50)),
                ("blobstore_path", models.CharField(max_length=200)),
                ("executable_path", models.CharField(max_length=200)),
                ("revision", models.FloatField(default=1.0)),
                ("timeout", models.IntegerField()),
                ("supported_platforms", models.CharField(max_length=50)),
                ("launcher_script", models.CharField(max_length=200)),
                ("result", models.CharField(default="", max_length=500)),
                ("result_timestamp", models.DateField()),
                ("console_output", models.CharField(default="", max_length=500)),
                ("return_code", models.IntegerField(default=1)),
                ("sample_testcase", models.CharField(default="", max_length=500)),
                ("max_testcases", models.IntegerField()),
                ("untrusted_content", models.BooleanField(default=False)),
                ("additional_environment_string", models.CharField(max_length=500)),
                ("stats_columns", models.CharField(max_length=50)),
                ("stats_column_descriptions", models.CharField(max_length=50)),
                ("builtin", models.BooleanField(default=False)),
                ("differential", models.BooleanField(default=False)),
                ("has_large_testcases", models.BooleanField(default=False)),
                ("data_bundle_name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bug_information", models.CharField(max_length=500)),
                ("test_case", models.BinaryField()),
                ("fixed", models.BooleanField(default=False)),
                ("one_time_crasher_flag", models.BooleanField(default=False)),
                ("comments", models.CharField(max_length=500)),
                ("absolute_path", models.CharField(max_length=200)),
                ("queue", models.CharField(max_length=50)),
                ("archived", models.BooleanField(default=False)),
                ("timestamp", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Ongoing"),
                            ("unreproducible", "Unreproducible"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("triaged", models.BooleanField(default=False)),
                ("has_bug_flag", models.BooleanField(default=False)),
                ("open", models.BooleanField(default=True)),
                ("testcase_path", models.CharField(max_length=200)),
                ("additional_metadata", models.CharField(max_length=500)),
                ("fuzzed_keys", models.CharField(max_length=200)),
                ("minimized_keys", models.CharField(max_length=200)),
                ("minidump_keys", models.CharField(max_length=200)),
                ("minimized_arguments", models.CharField(max_length=200)),
                ("disable_ubsan", models.BooleanField(default=False)),
                ("regression", models.CharField(max_length=200)),
                ("timeout_multiplier", models.FloatField(default=1.0)),
                ("archive_state", models.IntegerField()),
                ("redzone", models.IntegerField(default=128)),
                (
                    "fuzzer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.fuzzer",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PinguApi.job"
                    ),
                ),
            ],
        ),
    ]
