# Generated by Django 4.1.7 on 2023-03-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0003_fuzzer_testcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("fuzzer", models.CharField(max_length=50)),
                ("functions_covered", models.IntegerField()),
                ("functions_total", models.IntegerField()),
                ("edges_covered", models.IntegerField()),
                ("edges_total", models.IntegerField()),
                ("corpus_size_units", models.IntegerField()),
                ("corpus_size_bytes", models.IntegerField()),
                ("corpus_location", models.CharField(max_length=200)),
                ("corpus_backup_location", models.CharField(max_length=200)),
                ("quarantine_size_units", models.IntegerField()),
                ("quarantine_size_bytes", models.IntegerField()),
                ("quarantine_location", models.CharField(max_length=200)),
                ("html_report_url", models.BinaryField()),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.testcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.IntegerField(default=1)),
                ("bad_build", models.BooleanField(default=False)),
                (
                    "console_output",
                    models.CharField(
                        blank=True, default="", max_length=20000, null=True
                    ),
                ),
                ("bot_name", models.CharField(max_length=20)),
                (
                    "symbols",
                    models.CharField(
                        blank=True, default="", max_length=20000, null=True
                    ),
                ),
                ("timestamp", models.DateField()),
                (
                    "job",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.job",
                    ),
                ),
            ],
        ),
    ]
