# Generated by Django 4.1.7 on 2023-03-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0005_fuzztarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iteration", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("execs_per_sec", models.IntegerField()),
                ("date", models.DateField()),
                ("last_beat_time", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("task_payload", models.CharField(max_length=500)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PinguApi.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuzzTargetJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("last_run", models.DateField()),
                (
                    "engine",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.fuzzer",
                    ),
                ),
                (
                    "fuzzing_target",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.fuzztarget",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.job",
                    ),
                ),
            ],
        ),
    ]
