# Generated by Django 4.1.7 on 2023-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0007_testcasevariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=50)),
                ("probability", models.FloatField(default=1.0)),
                ("app_args", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
