# Generated by Django 4.1.7 on 2023-03-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("environment_string", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=400)),
                ("project", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("enabled", models.BooleanField(default=True)),
                ("archived", models.BooleanField(default=False)),
                ("platform", models.CharField(max_length=50)),
                (
                    "environment_string",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "custom_binary_path",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "custom_binary_filename",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "custom_binary_revision",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.jobtemplate",
                    ),
                ),
            ],
        ),
    ]
