# Generated by Django 4.1.7 on 2023-03-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0004_coverage_buildmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuzzTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=50)),
                ("binary", models.CharField(max_length=50)),
                (
                    "fuzzer_engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.fuzzer",
                    ),
                ),
            ],
        ),
    ]
