# Generated by Django 4.1.7 on 2023-03-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0006_statistic_fuzztargetjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("0", "Pending"),
                            ("1", "Reproducible"),
                            ("2", "Flaky"),
                            ("3", "Unreproducible"),
                        ],
                        default="0",
                    ),
                ),
                ("revision", models.IntegerField(default=1)),
                ("crash_type", models.CharField(default="", max_length=50)),
                ("crash_state", models.CharField(default="", max_length=50)),
                ("security_flag", models.BooleanField(default=False)),
                ("is_similar", models.BooleanField(default=False)),
                ("reproducer_key", models.CharField(default="", max_length=200)),
                ("platform", models.CharField(default="", max_length=50)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PinguApi.job"
                    ),
                ),
                (
                    "testcase_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PinguApi.testcase",
                    ),
                ),
            ],
        ),
    ]
