# Generated by Django 4.1.7 on 2023-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0008_trial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "VALID_NAME_REGEX",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("bucket_name", models.CharField(max_length=50)),
                (
                    "source",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("is_local", models.BooleanField(default=True)),
                ("timestamp", models.DateField()),
                ("sync_to_worker", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="open",
            new_name="opened",
        ),
    ]
