# Generated by Django 4.1.7 on 2023-03-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PinguApi", "0009_databundle_rename_open_testcase_opened"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcase",
            old_name="opened",
            new_name="open",
        ),
    ]
