env:
  # Django Backend SECRET_KEY
  SECRET_KEY: XXXXXX # CHANGE IT !!!

  # Django Configuration
  BACKEND_HOST: 127.0.0.1
  BACKEND_PORT: 8086

admin:
  username: admin # CHANGE IT !!!
  password: admin # CHANGE IT !!!
  email: admin@admin.com # CHANGE IT !!! 

